#!/bin/bash -e

tag=`date +%Y%m%d%H%M`
docker pull 'ubuntu:latest'

docker build \
  --tag "modernit1/cms-cnc:$tag" \
  --tag "modernit1/cms-cnc:latest" \
  CnC/.

docker build \
  --tag "modernit1/wordpress-cms:$tag" \
  --tag "modernit1/wordpress-cms:latest" \
  CMS/.
